---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubernetes-component
  labels:
    app: my-kubernetes-component
    backstage.io/kubernetes-id: my-kubernetes-component
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-kubernetes-component
  template:
    metadata:
      labels:
        app: my-kubernetes-component
        backstage.io/kubernetes-id: my-kubernetes-component
    spec:
      containers:
      - name: my-kubernetes-component
        {{ if .Values.image }}
        image: "ironcore864/go-hello-http:{{ .Values.image.tag }}"
        {{ else }}
        image: "ironcore864/go-hello-http:{{ .Chart.AppVersion }}"
        {{ end }}
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
        envFrom:
        - secretRef:
            name: mysecret
        ports:
        - containerPort: 8080
